services:
  gizmosql:
    image: gizmodata/gizmosql:v1.21.3-slim
    container_name: "aau_ais_gizmosql"
    init: true
    user: "${UID}:${GID}"
    environment:
      - GIZMOSQL_USERNAME=$GIZMOSQL__USER
      - GIZMOSQL_PASSWORD=$GIZMOSQL__PASSWORD
      - DATABASE_FILENAME=/opt/gizmosql/data/ais.duckdb
      - TLS_ENABLED=0
      - PRINT_QUERIES=1
      - INIT_SQL_COMMANDS_FILE=/home/app_user/init.sql
    ports:
      - 31337:31337
    volumes:
      - gizmosql_data:/opt/gizmosql/data
      - ./init.sql:/home/app_user/init.sql
    restart: unless-stopped

volumes:
  gizmosql_data: